export const migration = {
  version: 10,
  name: "accounts",
  sql: [
    "CREATE TABLE accounts (",
    "  account_id TEXT PRIMARY KEY,",
    "  revision INTEGER NOT NULL,",
    "  normalized_host TEXT NOT NULL,",
    "  numeric_user_id TEXT NOT NULL,",
    "  environment_kind TEXT NOT NULL CHECK (environment_kind IN ('github.com', 'ghes')),",
    "  login TEXT,",
    "  display_name TEXT,",
    "  authenticated_at_ms INTEGER,",
    "  credential_generation INTEGER,",
    "  credential_state TEXT NOT NULL CHECK (credential_state IN ('active', 'removing', 'removed')),",
    "  created_at_ms INTEGER NOT NULL,",
    "  updated_at_ms INTEGER NOT NULL,",
    "  UNIQUE(normalized_host, numeric_user_id)",
    ");",
    "CREATE TABLE gateway_preferences (",
    "  singleton_id INTEGER PRIMARY KEY CHECK (singleton_id = 1),",
    "  revision INTEGER NOT NULL,",
    "  default_account_id TEXT REFERENCES accounts(account_id),",
    "  updated_at_ms INTEGER NOT NULL",
    ");",
    "CREATE TABLE account_model_preferences (",
    "  account_id TEXT PRIMARY KEY REFERENCES accounts(account_id),",
    "  revision INTEGER NOT NULL,",
    "  model_id TEXT NOT NULL,",
    "  validity TEXT NOT NULL CHECK (validity IN ('valid', 'invalid')),",
    "  catalog_generation INTEGER NOT NULL,",
    "  updated_at_ms INTEGER NOT NULL",
    ");",
    "INSERT INTO gateway_preferences (singleton_id, revision, default_account_id, updated_at_ms) VALUES (1, 0, NULL, 0);",
  ].join("\n"),
} as const;
