export const migration = {
  version: 20,
  name: "telemetry",
  sql: [
    "CREATE TABLE usage_buckets (",
    "  utc_hour_ms INTEGER NOT NULL,",
    "  account_id TEXT NOT NULL,",
    "  protocol TEXT NOT NULL CHECK (protocol IN (",
    "    'openai_chat', 'openai_responses_native', 'openai_responses_bridge', 'anthropic', 'ollama'",
    "  )),",
    "  resolved_model TEXT NOT NULL,",
    "  outcome TEXT NOT NULL CHECK (outcome IN (",
    "    'success', 'client_error', 'authentication_error', 'overloaded',",
    "    'upstream_error', 'timeout', 'aborted', 'internal_error'",
    "  )),",
    "  request_count INTEGER NOT NULL,",
    "  error_count INTEGER NOT NULL,",
    "  input_tokens INTEGER NOT NULL,",
    "  output_tokens INTEGER NOT NULL,",
    "  cache_tokens INTEGER NOT NULL,",
    "  latency_sum_ms REAL NOT NULL,",
    "  latency_max_ms REAL NOT NULL,",
    "  PRIMARY KEY(utc_hour_ms, account_id, protocol, resolved_model, outcome)",
    ");",
    "CREATE INDEX usage_buckets_utc_hour_ms ON usage_buckets(utc_hour_ms);",
    "CREATE TABLE operational_events (",
    "  event_id INTEGER PRIMARY KEY AUTOINCREMENT,",
    "  occurred_at_ms INTEGER NOT NULL,",
    "  kind TEXT NOT NULL,",
    "  severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'error')),",
    "  metadata_json TEXT NOT NULL",
    ");",
    "CREATE INDEX operational_events_occurred ON operational_events(occurred_at_ms, event_id);",
    "CREATE TABLE telemetry_state (",
    "  singleton_id INTEGER PRIMARY KEY CHECK (singleton_id = 1),",
    "  dropped_usage_updates INTEGER NOT NULL,",
    "  dropped_operational_events INTEGER NOT NULL,",
    "  updated_at_ms INTEGER NOT NULL",
    ");",
    "INSERT INTO telemetry_state (singleton_id, dropped_usage_updates, dropped_operational_events, updated_at_ms) VALUES (1, 0, 0, 0);",
  ].join("\n"),
} as const;
