export const migration = {
  version: 30,
  name: "responses_history",
  sql: [
    "CREATE TABLE responses_history_state (",
    "  singleton_id INTEGER PRIMARY KEY CHECK (singleton_id = 1),",
    "  revision INTEGER NOT NULL,",
    "  next_insertion_seq INTEGER NOT NULL,",
    "  updated_at_ms INTEGER NOT NULL",
    ");",
    "CREATE TABLE responses (",
    "  response_id TEXT PRIMARY KEY,",
    "  insertion_seq INTEGER NOT NULL UNIQUE,",
    "  created_at_ms INTEGER NOT NULL,",
    "  expires_at_ms INTEGER NOT NULL",
    ");",
    "CREATE TABLE response_calls (",
    "  response_id TEXT NOT NULL REFERENCES responses(response_id) ON DELETE CASCADE,",
    "  ordinal INTEGER NOT NULL,",
    "  call_id TEXT NOT NULL,",
    "  kind TEXT NOT NULL CHECK (kind IN ('function_call', 'custom_tool_call', 'tool_search_call')),",
    "  item_json TEXT NOT NULL,",
    "  PRIMARY KEY(response_id, ordinal)",
    ");",
    "CREATE INDEX responses_expires_at_ms ON responses(expires_at_ms);",
    "CREATE INDEX response_calls_call_id ON response_calls(call_id);",
    "INSERT INTO responses_history_state (singleton_id, revision, next_insertion_seq, updated_at_ms) VALUES (1, 0, 1, 0);",
  ].join("\n"),
} as const;
